name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go in build directory
      run: mkdir -p build;
    - name: Run cmake and build
      working-directory: ./build
      run: cmake .. && cmake --build .;
    - name: Print Main
      working-directory: ./build
      run: ./Huitamericain
