name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cppcheck
      run: sudo apt install cppcheck -y
    - name: Go in build directory
      run: mkdir -p build;
    - name: Run cmake
      working-directory: ./build
      run: time cmake ..;
    - name: Run cmake build
      working-directory: ./build
      run: time cmake --build .;
    - name: Print Main
      working-directory: ./build
      run: ./Huitamericain;
    - name: Cpp check code
      run: time cppcheck --enable=all --std=c++11 src;
    - name: Cpp check build
      run: time cppcheck --enable=all --std=c++11 --cppcheck-build-dir=./build src;
